export const clients = [
  {
    slug: "sumi-jo",
    name: "Sumi Jo",
    discipline: "Soprano",
    image: 24,
    alt: "Aaron with soprano Sumi Jo",
    gallery: [23, 24],
    bio: "South Korean coloratura soprano Sumi Jo has built an international career across the opera and concert stage. Her early collaborations with Herbert von Karajan at the Salzburg Festival helped introduce her distinctive voice to audiences around the world.",
    role: "Digital & Social Media Strategy",
    summary: "A considered digital presence for an unmistakable voice.",
    work: "I work with Sumi Jo on digital and social media strategy and related marketing, translating an international performing career into clear, engaging communication across platforms.",
    scope: [
      "Social media strategy",
      "Digital communications",
      "Artist marketing",
    ],
    source: "https://www.laphil.com/people/sumi-jo",
    sourceName: "Los Angeles Philharmonic",
  },
  {
    slug: "xian-zhang",
    name: "Xian Zhang",
    discipline: "Conductor",
    image: 11,
    alt: "Aaron in conversation with conductor Xian Zhang",
    gallery: [11, 12, 7],
    bio: "Xian Zhang is an international conductor and Music Director of the Seattle Symphony. Her work spans symphonic and operatic repertoire, with appearances on major concert stages around the world.",
    role: "Digital & Social Media Strategy",
    summary:
      "Connecting life on the podium with audiences beyond the concert hall.",
    work: "My work with Xian Zhang focuses on digital and social media strategy and communications, supporting a coherent public presence around her work as a conductor.",
    scope: [
      "Social media strategy",
      "Digital communications",
      "Audience development",
    ],
    source:
      "https://seattlesymphonypress.squarespace.com/pressreleases/2026/2/19/music-director-xian-zhang-and-the-seattle-symphony-announce-the-20262027-season",
    sourceName: "Seattle Symphony",
  },
  {
    slug: "jasmine-choi",
    name: "Jasmine Choi",
    discipline: "Flutist",
    image: 15,
    alt: "Aaron with flutist Jasmine Choi",
    gallery: [15, 14, 17, 16],
    bio: "Jasmine Choi is an internationally active flutist whose career encompasses solo performance, recording, and teaching. A graduate of Curtis and Juilliard, she previously served as principal flute of the Vienna Symphony and associate principal flute of the Cincinnati Symphony.",
    role: "Digital & Social Media Strategy",
    summary: "An artist’s identity, thoughtfully connected across platforms.",
    work: "I work with Jasmine on digital marketing, social media, branding, and web presence—bringing these parts of her public identity into a coherent whole.",
    scope: [
      "Digital marketing",
      "Social media strategy",
      "Branding",
      "Web presence",
    ],
    source:
      "https://music.indiana.edu/faculty/new-faculty-resonance/new-faculty-profiles/choi-jasmine.html",
    sourceName: "Indiana University Jacobs School of Music",
  },
  {
    slug: "hudson-zhang-studio",
    name: "Hudson Zhang Studio",
    discipline: "Visual art",
    image: 5,
    alt: "Aaron at Hudson Zhang’s book launch reception at the Harvard Club of New York City",
    gallery: [5, 6],
    bio: "Hudson Shaoxia Zhang is a visual artist whose golf-course landscapes explore the relationship between art, place, and the culture of the game. His paintings and writings bring a painter’s perspective to a familiar sporting landscape.",
    role: "Director of Media and Communications",
    summary: "Art, landscape, and golf culture—in a shared frame.",
    work: "As Director of Media and Communications, I work across the studio’s digital branding, social media, web presence, marketing, communications, and exhibition promotion. The work also helps develop the studio’s positioning around art and golf culture.",
    scope: [
      "Digital branding & positioning",
      "Media & communications",
      "Social media & web presence",
      "Exhibition promotion",
    ],
    source: "https://www.hudsonzhang.com/newsdetail?article_id=236",
    sourceName: "Hudson Zhang — official studio website",
  },
  {
    slug: "new-york-star",
    name: "New York Star Artist Management",
    discipline: "Artist management",
    image: 27,
    alt: "Aaron with the New York Star Artist Management team",
    gallery: [27, 7, 18],
    bio: "New York Star Artist Management is a New York–based arts management organization whose activities include artist representation, concert and event production, and music education.",
    role: "Digital promotion & concert marketing",
    summary: "Helping live performances find their audiences.",
    work: "My work with New York Star Artist Management has included digital promotion and concert marketing, with support for performances at Carnegie Hall and Alice Tully Hall.",
    scope: ["Digital promotion", "Concert marketing", "Ticket-sales support"],
    source: "https://www.nystarmanage.com/",
    sourceName: "New York Star Artist Management — official website",
    entries: [
      [
        "Yiruma — Carnegie Hall, Isaac Stern Auditorium",
        "I contributed to the digital promotion surrounding the concert, which sold out Isaac Stern Auditorium.",
      ],
      [
        "Danny Koo — Carnegie Hall",
        "I assisted with promotion for violinist Danny Koo’s recital.",
      ],
      [
        "Tan Jing — Alice Tully Hall",
        "I assisted with concert promotion and ticket-sales marketing.",
      ],
    ],
  },
  {
    slug: "401-entertainment",
    name: "401 Entertainment",
    discipline: "Entertainment",
    image: null,
    alt: "",
    gallery: [],
    bio: "A collaboration focused on social media, artist promotion, and live entertainment.",
    role: "Social media & promotional campaigns",
    summary: "Reaching listeners across genres and generations.",
    work: "I work with 401 Entertainment on social media and promotional campaigns, including support surrounding Chaeyoung Lee’s concert appearance alongside Jo Sung-mo and Bada of S.E.S. My work also includes broader social media promotional support for the organization.",
    scope: ["Social media promotion", "Artist campaigns", "Concert promotion"],
    source: "",
    sourceName: "",
  },
  {
    slug: "sumi-jo-competition",
    name: "Sumi Jo International Singing Competition",
    discipline: "International competition",
    image: null,
    alt: "Sumi Jo International Singing Competition official artwork",
    gallery: [],
    bio: "An international singing competition bringing together singers from around the world.",
    role: "Strategic Digital Promotion",
    summary: "An international stage. A global applicant pool.",
    work: "I created strategic digital promotional campaigns for the competition, supporting an international applicant pool of more than 500 singers from 55 countries.",
    scope: [
      "Promotional strategy",
      "Digital campaigns",
      "International audience outreach",
    ],
    source: "",
    sourceName: "",
    stats: [
      ["500+", "Applications"],
      ["55", "Countries"],
    ],
    statsNote:
      "Competition-wide application figures; digital promotion was one part of the wider effort.",
    event: {
      src: "/images/competition-event.webp",
      width: 1280,
      height: 854,
      alt: "Singers gathered onstage at the Sumi Jo International Singing Competition",
      caption: "Sumi Jo International Singing Competition",
      credit: "Alterego",
    },
  },
  {
    slug: "opera-italiana",
    name: "Opera Italiana is in the Air",
    discipline: "Opera festival",
    image: null,
    alt: "Opera Italiana is in the Air official logo",
    gallery: [],
    bio: "A free public event bringing live opera into a shared, open-air setting.",
    role: "Strategic Digital Promotion",
    summary: "Live opera, open to everyone.",
    work: "I have created strategic promotional campaigns across multiple festival seasons. The free public event has drawn live audiences of approximately 3,000–5,000 attendees.",
    scope: [
      "Promotional strategy",
      "Digital campaigns",
      "Multi-season festival promotion",
    ],
    source: "",
    sourceName: "",
    stats: [["3,000–5,000", "Approximate attendees"]],
    statsNote:
      "An approximate event attendance range, reflecting the festival’s overall audience.",
    event: {
      src: "/images/opera-event.webp",
      width: 1600,
      height: 1067,
      alt: "An audience gathered around an outdoor bandshell for Opera Italiana is in the Air",
      caption: "Opera Italiana is in the Air",
      credit: "STUDIOP23",
    },
  },
];
export const services = [
  {
    name: "Social media strategy",
    line: "Build an audience with a reason to stay.",
    description:
      "A clear role for every platform and a point of view that runs through the content. Strategy grounded in the experience of building Classic Divinity to more than one million followers.",
    items: [
      "Platform strategy & positioning",
      "Content planning & editorial calendars",
      "Audience development",
      "Campaigns, analytics & growth",
    ],
  },
  {
    name: "Digital marketing",
    line: "Give the campaign a clear direction.",
    description:
      "Digital campaigns built around the audience, the moment, and the message. From an artist announcement to a cultural event, each channel has a specific job to do.",
    items: [
      "Integrated campaign strategy",
      "Audience targeting",
      "Cultural & event promotion",
      "Campaign planning",
    ],
  },
  {
    name: "Web design & digital presence",
    line: "Make the first impression a considered one.",
    description:
      "Websites that express a distinct identity and make the next step easy. I connect visual direction, content, and user experience into a coherent digital presence.",
    items: [
      "Website strategy & visual direction",
      "Content architecture",
      "User experience",
      "Design & implementation",
    ],
  },
  {
    name: "Content & creative direction",
    line: "Find the story worth telling.",
    description:
      "An editorial perspective for the way a brand or artist shows up. Concepts, narratives, and visual systems that give individual pieces of content a shared purpose.",
    items: [
      "Digital storytelling",
      "Editorial & visual direction",
      "Campaign concepts",
      "Content systems",
    ],
  },
  {
    name: "Arts & entertainment marketing",
    line: "Bring people closer to the work.",
    description:
      "Marketing informed by the context of creative work and the practical demands of a performance, exhibition, or release. An international outlook, with attention to the audience in front of you.",
    items: [
      "Artist positioning",
      "Concert & exhibition promotion",
      "Ticket-sales support",
      "International audience development",
    ],
  },
];
export const projects = [
  {
    slug: "classic-divinity",
    name: "Classic Divinity",
    category: "Audience building / Cultural media",
    lead: "Classical music, in the digital conversation.",
    role: "Founder",
    stat: "1M+",
    statLabel: "Followers across Instagram & TikTok",
    image: null,
    context:
      "I founded Classic Divinity as a classical music media platform on Instagram and TikTok. Today, it reaches more than one million followers across its platforms.",
    approach:
      "The platform brings together digital storytelling, artist promotion, and a close understanding of how people discover music online. It is hands-on experience in building an audience—not just advising one.",
    result:
      "Classic Divinity has worked with or partnered with Il Volo, Sumi Jo, Jasmine Choi, the Sumi Jo International Singing Competition, and Opera Italiana is in the Air, among others.",
    note: "Promotional collaboration posts have also involved musicians including Jonas Kaufmann, Sol Gabetta, Plácido Domingo, and Sondra Radvanovsky. These collaborations are distinct from my direct consulting relationships.",
    scope: [
      "Social media strategy",
      "Editorial direction",
      "Artist promotion",
      "Audience development",
    ],
  },
  {
    slug: "hudson-zhang-studio",
    name: "Hudson Zhang Studio",
    category: "Visual art / Brand & communications",
    lead: "A wider conversation around art and golf.",
    role: "Director of Media and Communications",
    stat: "Art × Golf",
    statLabel: "A distinct cultural point of view",
    image: 5,
    context:
      "Hudson Zhang’s studio works at the intersection of visual art and golf culture. Its digital presence needs to make that context legible without losing the particular character of the artwork.",
    approach:
      "My role brings together digital branding, social media strategy, web presence, marketing, communications, and exhibition promotion, helping develop a consistent public identity for the studio.",
    result:
      "An ongoing communications remit spanning the studio’s platforms and the promotion of its work, exhibitions, and cultural positioning.",
    note: "Pictured: Hudson Zhang’s book launch reception at the Harvard Club of New York City, from Aaron’s personal archive.",
    scope: [
      "Brand positioning",
      "Digital presence",
      "Media & communications",
      "Exhibition promotion",
    ],
  },
];
